services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-container
    ports:
      - "8081:80"
    environment:
      - NODE_ENV=production
    networks:
      - auth-project

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-container
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env
    networks:
      - auth-project
    depends_on:
      postgres:
        condition: service_healthy
  
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - auth-project
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  auth-project:
    driver: bridge

volumes:
  postgres_data:
