services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-container
    ports:
      - "8081:80"
    environment:
      - NODE_ENV=production
    networks:
      - auth-project

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-container
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=production
    depends_on:
      - frontend
    networks:
      - auth-project

networks:
  auth-project:
    driver: bridge
