export { DashboardPage } from './dashboard/DashboardPage'
export { LoginPage } from './login/LoginPage'
export { RegisterPage } from './register/RegisterPage'
export { ActivatePage } from './activatePage/activatePage'
export { PasswordPage } from './passwordPage/Password'