FROM maven:3-openjdk-17-slim AS build

WORKDIR /api

COPY . .

RUN mvn clean package -DskipTests

FROM openjdk:17-jdk-slim

WORKDIR /api

COPY --from=build /api/target/api-0.0.1-SNAPSHOT.jar /api/api-0.0.1-SNAPSHOT.jar

COPY ./.env /api/.env

EXPOSE 8080

ENV ENV_DIRECTORY="/api"

CMD ["java", "-jar", "api-0.0.1-SNAPSHOT.jar"]
