FROM openjdk:17-jdk-slim

WORKDIR /api

COPY ./target/api-0.0.1-SNAPSHOT.jar /api/api-0.0.1-SNAPSHOT.jar

COPY ./target/.env /api/.env

EXPOSE 8080

CMD ["java", "-jar", "api-0.0.1-SNAPSHOT.jar"]
